### ISSUE TITLE
Missing repo description, empty readme and code

### ISSUE THREAD

**Issue by cybercamphackathon** [UleRobots/ROS-cipherer#1]

**Comment by cybercamphackathon** [comment]
the repo doesnt have any description still. reopen this

**Comment by cybercamphackathon** [comment]
see https://github.com/UleRobots/ROS-cipherer/issues/4 <https://github.com/UleRobots/ROS-cipherer/issues/4> and https://github.com/UleRobots/ROS-cipherer/issues/6 <https://github.com/UleRobots/ROS-cipherer/issues/6>

**Comment by UleRobots** [comment]
Hemos añadido la descripción. El readme lo completaremos acorde al issue #6
